# Generated by Django 5.2.8 on 2025-12-04 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0002_diagnostic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='business_model_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='industry_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='StartupOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('received_investment', models.BooleanField(default=False)),
                ('investment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('accepted_in_accelerator', models.BooleanField(default=False)),
                ('monthly_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('founder_feedback_score', models.IntegerField(null=True)),
                ('pivot_occurred', models.BooleanField(default=False)),
                ('diagnostic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='diagnostic.diagnostic')),
            ],
        ),
    ]
