# Generated by Django 5.2.8 on 2026-01-09 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0007_webhookconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback_text', models.TextField(blank=True, null=True)),
                ('corrected_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='diagnostic.diagnostic')),
            ],
        ),
    ]
