# Generated by Django 5.2.8 on 2026-01-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0008_analysisfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='recommendation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
